### ISSUE TITLE
[Krb5LoginModule] authentication failed 

### ISSUE THREAD

**Issue by tunguyenht** [cybertony/HdfsClient#1]
hope you help me
[Krb5LoginModule] authentication failed 

hadoop.principal=xx@xxx.CORP
hadoop.password=XXX

[libdefaults]
 default_realm = xxxxx.CORP
 # kdc will be obtained through DNS SRV
 dns_lookup_kdc = true
 forwardable = true
 default_tkt_enctypes = arcfour-hmac-md5
 ticket_lifetime = 10h
 default_etypes = arcfour-hmac-md5
 default_etypes_des = des-cbc-crc
 
[domain_realm]
 .xxx.corp = xxx.CORP
 xxxx.corp = xxx.CORP

**Comment by tunguyenht** [comment]
Debug is  true storeKey false useTicketCache false useKeyTab false doNotPrompt false ticketCache is null isInitiator true KeyTab is null refreshKrb5Config is false principal is null tryFirstPass is false useFirstPass is false storePass is false clearPass is false
		[Krb5LoginModule] user entered username: xxx@XXX.CORP

		[Krb5LoginModule] authentication failed 
null (68)
Exception in thread "main" javax.security.auth.login.LoginException: null (68)
	at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:804)
	at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
	at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
	at com.tony.hdfs.HDFSClientKerberos.loginWithUserPassword(HDFSClientKerberos.java:101)
	at com.tony.hdfs.HDFSClient.getConf(HDFSClient.java:54)
	at com.tony.hdfs.HDFSClient.main(HDFSClient.java:72)
Caused by: KrbException: null (68)
	at sun.security.krb5.KrbAsRep.<init>(KrbAsRep.java:76)
	at sun.security.krb5.KrbAsReqBuilder.send(KrbAsReqBuilder.java:316)
	at sun.security.krb5.KrbAsReqBuilder.action(KrbAsReqBuilder.java:361)
	at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:766)
	... 15 more
Caused by: KrbException: Identifier doesn't match expected value (906)
	at sun.security.krb5.internal.KDCRep.init(KDCRep.java:140)
	at sun.security.krb5.internal.ASRep.init(ASRep.java:64)
	at sun.security.krb5.internal.ASRep.<init>(ASRep.java:59)
	at sun.security.krb5.KrbAsRep.<init>(KrbAsRep.java:60)
	... 18 more
